"""
random:
    https://docs.python.org/3/library/random.html
"""
from player import Player

suit_list = ['Spade', 'Diamond', 'Club', 'Heart']
numerical_value_list = [2, 3, 4, 5, 6, 7, 8, 9, 10]
face_value_list = ['Jack', 'Queen', 'King', 'Ace', 'Joker']
deck_point_count = 50
value_range = range(2, 11)



def test_player_initialization():
    """tests the main deck generated by 'generated_deck()' method.
        needs to be parameterized"""

    player = Player("Steve", deck_point_count, suit_list)
    player_hand = player.player_starting_hand.hand

    for card in player_hand:
        assert card.value in value_range and card.suit in suit_list

